provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_linux64
github:
  branch_name: main
  tooling_branch_name: main
